services:
  - type: web
    name: inventario-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MYSQL_HOST
        value: "kodama.proxy.rlwy.net"
      - key: MYSQL_PORT
        value: "40247"
      - key: MYSQL_DATABASE
        value: "railway"
      - key: MYSQLUSER
        value: "root"
      - key: MYSQLPASSWORD
        value: "IjDdTdBqyzXfNxLyycYPZhbTBAsGCJnH"
      - key: MYSQL_SSL
        value: "true"
